 services:
    todo-list-api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
           - '3000:3000'
        environment:
            - PORT=3000
            - NODE_ENV=development
        volumes:
            - ./src:/usr/src/app/src
    db:
        image: mysql
        ports:
            - '3307:3307'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=todo_list_api
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=dev-123
            - MYSQL_TCP_PORT=3307
